#!/usr/bin/env node
/* Writes the canonical, Open Graph, Twitter and JSON-LD block into every
   public page, between the two markers below.

     node scripts/build-seo.js
     node scripts/build-seo.js --check     (fails if any page is out of date)

   Nothing here writes body copy. The title and description are read out of
   each page's existing <head> and reused as-is, so the wording stays whatever
   was written by hand. Re-running after editing a title updates the tags.

   The markers are ordinary HTML comments, so scripts/minify.js strips them
   from dist/ and only the tags themselves ship.

   URL FORM. vercel.json sets "cleanUrls": true, so /laws.html is a 308 to
   /laws and the extensionless URL is the real one. Canonicals, og:url and the
   sitemap therefore all drop the extension. If this ever moves to Firebase
   Hosting, whose firebase.json sets cleanUrls:false, flip CLEAN_URLS to false
   here and re-run both this and build-search-index.js. */

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { publicPages } = require('./build-search-index');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://peopleforanimalsindia.org';
const CLEAN_URLS = true;

const OPEN = '<!-- seo:start  generated by scripts/build-seo.js - do not edit by hand -->';
const CLOSE = '<!-- seo:end -->';
const BLOCK = new RegExp(`\\n?[ \\t]*${OPEN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${CLOSE}\\n?`, 'g');

/* The one date this script cannot read off the page. Google requires
   datePosted on a JobPosting and will not show the listing without it.
   Set it to the day the Zonal Head opening actually went up. */
const CAREERS_POSTED = '2026-08-28';
const CAREERS_VALID_THROUGH = '2027-02-28';

/* Facts below are taken from assets/chrome-footer.html, which is what the
   site already tells visitors. Nothing here is invented. */
const ORG = {
  '@type': ['NGO', 'AnimalShelter'],
  '@id': `${SITE}/#organisation`,
  name: 'People for Animals',
  alternateName: 'PFA',
  url: `${SITE}/`,
  logo: `${SITE}/img/logo.png`,
  telephone: '+91-11-2081-8191',
  address: {
    '@type': 'PostalAddress',
    streetAddress: '4-T, DCM Building, 16 Barakhamba Road',
    addressLocality: 'New Delhi',
    postalCode: '110001',
    addressCountry: 'IN'
  },
  sameAs: [
    'https://www.facebook.com/people4animals/',
    'https://www.instagram.com/pfa.official/',
    'https://x.com/pfaindia'
  ]
};

/* Which JSON-LD each page carries, beyond the breadcrumb every page gets.
   Deliberately short. FAQPage is not here because Google restricted FAQ rich
   results to government and health sites in August 2023, and Event is not here
   because the only event on events.html has already been held; both become
   worth adding the day that changes. */
function pageSchema(file) {
  if (file === 'index.html') {
    return [
      ORG,
      {
        '@type': 'WebSite',
        '@id': `${SITE}/#website`,
        url: `${SITE}/`,
        name: 'People for Animals',
        publisher: { '@id': `${SITE}/#organisation` },
        potentialAction: {
          '@type': 'SearchAction',
          target: { '@type': 'EntryPoint', urlTemplate: `${SITE}/search?q={search_term_string}` },
          'query-input': 'required name=search_term_string'
        }
      }
    ];
  }
  if (file === 'careers.html') {
    return [{
      '@type': 'JobPosting',
      title: 'Zonal Head',
      description: 'PFA\u2019s coordinator for every Unit in a Zone: growing the network, mentoring local leadership, and making sure a cruelty complaint becomes a case that survives prosecution.',
      datePosted: CAREERS_POSTED,
      validThrough: CAREERS_VALID_THROUGH,
      employmentType: 'FULL_TIME',
      hiringOrganization: { '@id': `${SITE}/#organisation` },
      jobLocationType: 'TELECOMMUTE',
      applicantLocationRequirements: { '@type': 'Country', name: 'India' },
      jobLocation: {
        '@type': 'Place',
        address: { '@type': 'PostalAddress', addressCountry: 'IN' }
      },
      baseSalary: {
        '@type': 'MonetaryAmount',
        currency: 'INR',
        value: { '@type': 'QuantitativeValue', value: 35000, unitText: 'MONTH' }
      },
      directApply: true
    }];
  }
  if (file === 'founder.html') {
    return [{
      '@type': 'Person',
      name: 'Maneka Sanjay Gandhi',
      jobTitle: 'Founder',
      affiliation: { '@id': `${SITE}/#organisation` },
      image: `${SITE}/img/founder-portrait-1536.jpg`
    }];
  }
  return [];
}

function urlFor(file) {
  if (file === 'index.html') return `${SITE}/`;
  return `${SITE}/` + (CLEAN_URLS ? file.replace(/\.html$/, '') : file);
}

function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

/* JSON inside <script> must not be able to close the tag. Same guard
   lib/routes/product-page.js uses. */
function safeJson(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

function readTag(html, re) {
  const m = re.exec(html);
  return m ? m[1].trim() : '';
}

/* The title carries " | People for Animals" for the tab and the search result.
   og:title sits under a card that already shows the site name, so the suffix
   is dropped there rather than said twice. */
function ogTitle(title) {
  return title.replace(/\s*[|\u00b7\u2013-]\s*People for Animals\s*$/i, '').trim() || title;
}

function block(file, html) {
  const title = readTag(html, /<title>([\s\S]*?)<\/title>/i);
  const description = readTag(html, /<meta\s+name=["']description["']\s+content=["']([\s\S]*?)["']\s*\/?>/i);
  const url = urlFor(file);
  const image = `${SITE}/img/og-default.jpg`;

  const graph = [
    ...pageSchema(file).map((n) => ({ '@context': 'https://schema.org', ...n })),
    file === 'index.html' ? null : {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
        { '@type': 'ListItem', position: 2, name: ogTitle(title), item: url }
      ]
    }
  ].filter(Boolean);

  const lines = [
    OPEN,
    `<link rel="canonical" href="${esc(url)}">`,
    `<meta property="og:site_name" content="People for Animals">`,
    `<meta property="og:locale" content="en_IN">`,
    `<meta property="og:type" content="${file === 'index.html' ? 'website' : 'article'}">`,
    `<meta property="og:title" content="${esc(ogTitle(title))}">`,
    description ? `<meta property="og:description" content="${esc(description)}">` : '',
    `<meta property="og:url" content="${esc(url)}">`,
    `<meta property="og:image" content="${esc(image)}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:alt" content="A People for Animals caregiver with a rescued animal">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:site" content="@pfaindia">`,
    `<meta name="twitter:title" content="${esc(ogTitle(title))}">`,
    description ? `<meta name="twitter:description" content="${esc(description)}">` : '',
    `<meta name="twitter:image" content="${esc(image)}">`,
    ...graph.map((n) => `<script type="application/ld+json">${safeJson(n)}</script>`),
    CLOSE
  ].filter(Boolean);

  return '\n' + lines.map((l) => '  ' + l).join('\n') + '\n';
}

function apply(html, file) {
  const stripped = html.replace(BLOCK, '\n');
  const at = stripped.search(/<\/head>/i);
  if (at < 0) return null;
  return stripped.slice(0, at) + block(file, stripped).replace(/^\n/, '') + stripped.slice(at);
}

function run(check) {
  const stale = [];
  let written = 0;
  publicPages().forEach((file) => {
    const p = path.join(ROOT, file);
    const html = fs.readFileSync(p, 'utf8');
    const next = apply(html, file);
    if (next === null) { stale.push(`${file}: no </head>`); return; }
    if (next === html) return;
    if (check) { stale.push(file); return; }
    fs.writeFileSync(p, next);
    written++;
  });
  if (check) {
    if (stale.length) {
      console.error('Out of date, run: node scripts/build-seo.js\n  ' + stale.join('\n  '));
      process.exit(1);
    }
    console.log('Every public page carries a current SEO block.');
    return;
  }
  console.log(`Updated ${written} of ${publicPages().length} public pages.`);
}

module.exports = { block, urlFor, publicPages, CLEAN_URLS };

if (require.main === module) run(process.argv.includes('--check'));
